version: '2'

services:
  web:
    image: olafrv/limesurvey:3.15
    container_name: limesurvey_web
    restart: always
    networks:
      - proxy
    depends_on:
      - db
  db:
    image: mysql:5.7.24
    container_name: limesurvey_mysql
    restart: always
    networks:
      - proxy
    volumes:
      - mysql:/var/lib/mysql
    env_file:
      - mysql.env
#    environment:
#      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
#      MYSQL_HOST: "localhost"
#      MYSQL_PORT: "3306"
#      MYSQL_ROOT_PASSWORD: "root"
#      MYSQL_DATABASE: "limesurvey"
#      MYSQL_LOYALTY_DATABASE: "limesurvey"
#      MYSQL_USER: "limesurvey"
#      MYSQL_PASSWORD: "limesurvey"
  pma:
     image: phpmyadmin/phpmyadmin:4.7
     container_name: limesurvey_pma
     restart: always
     networks:
       - proxy
     env_file:
       - phpmyadmin.env
#     environment:
#       PMA_ABSOLUTE_URI: https://app.daycohost.com/limesurvey_pma/
#       PMA_HOST: "limesurvey_mysql"
#       PMA_PORT: "3306"
#       PMA_USER: "root"
#       PMA_PASSWORD: "root"
     depends_on:
       - db
volumes:
    mysql:

networks:
  proxy:
    external:
      name: proxy
